name: doxygen-deploy

on:
  push:
    branches: [ main ] \

jobs:
  deploy-GroupProject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/GroupProject/webfile
        run: doxygen Doxyfile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/GroupProject/webfile/html
